version: "3"

services:

  litecoin-node1:
    image: coinflow/ltc-node:0.21.4
    container_name: litecoin-node1
    restart: on-failure:3
    environment:
      - TZ=Europe/London
      - LITE_ADDNODE=litecoin-node2
    ports:
      - "19332:19332"
      - "19333:19333"
      - "1222:1222"
    volumes:
      - litecoin-local-node1-data:/opt/litecoin/.litecoin/db
      - ./config-local/litecoin/litecoin.conf:/opt/litecoin/.litecoin/litecoin.conf
  litecoin-node2:
    image: coinflow/ltc-node:0.21.4
    container_name: litecoin-node2
    restart: on-failure:3
    environment:
      - TZ=Europe/London
      - LITE_ADDNODE=litecoin-node1
    ports:
      - "19334:19332"
      - "19335:19333"
      - "1223:1222"
    volumes:
      - litecoin-local-node2-data:/opt/litecoin/.litecoin/db
      - ./config-local/litecoin/litecoin.conf:/opt/litecoin/.litecoin/litecoin.conf

  dogecoin-node1:
    image: coinflow/doge-node:1.14.9
    container_name: dogecoin-node1
    restart: on-failure:3
    environment:
      - TZ=Europe/London
      - DOGE_ADDNODE=dogecoin-node2
    ports:
      - "44555:44555"
      - "44556:44556"
      - "1322:1322"
    volumes:
      - dogecoin-local-node1-data:/opt/dogecoin/.dogecoin/db
      - ./config-local/dogecoin/dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf
  dogecoin-node2:
    image: coinflow/doge-node:1.14.9
    container_name: dogecoin-node2
    restart: on-failure:3
    environment:
      - TZ=Europe/London
      - DOGE_ADDNODE=dogecoin-node1
    ports:
      - "44557:44555"
      - "44558:44556"
      - "1323:1322"
    volumes:
      - dogecoin-local-node2-data:/opt/dogecoin/.dogecoin/db
      - ./config-local/dogecoin/dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf

volumes:
  litecoin-local-node1-data:
  litecoin-local-node2-data:
  dogecoin-local-node1-data:
  dogecoin-local-node2-data: