version: "3"

services:

  litecoin:
    image: coinflow/ltc-node:0.21.4
    container_name: litecoin
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - "19332:19332"
      - "19333:19333"
    volumes:
      - litecoin-local-data:/opt/litecoin/.litecoin/db
      - ./config-local/litecoin/litecoin.conf:/opt/litecoin/.litecoin/litecoin.conf

  dogecoin:
    image: coinflow/doge-node:1.14.9
    container_name: dogecoin
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - "44555:44555"
      - "44556:44556"
    volumes:
      - dogecoin-local-data:/opt/dogecoin/.dogecoin/db
      - ./config-local/dogecoin/dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf

volumes:
  litecoin-local-data:
  dogecoin-local-data: